CREATE TABLE `customer` (
  `CUST_ID` int(15) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(110) NOT NULL,
  `AGE` int(15) unsigned NOT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;